# Generated by Django 3.1.2 on 2020-10-03 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='created_detetime',
            new_name='created_datetime',
        ),
    ]
